export type { Sugestao, StatusSugestao, TipoSugestao } from './model/types'
export { SUGESTOES_HISTORICO_QUERY_KEY, SUGESTOES_PENDENTES_QUERY_KEY, useSugestoesHistorico, useSugestoesPendentes } from './model/use-sugestoes'
export { TIPO_SUGESTAO_LABEL } from './lib/rotulos'
export { textoBaseDaSugestao, tituloDaSugestao } from './lib/frase'
export type { LookupsFraseSugestao } from './lib/frase'
